INHERIT: ../../mkdocs-base.yml
site_name: DepthFlow
site_description: ğŸŒŠ Images to â†’ 3D Parallax effect video. A free and open source ImmersityAI alternative
site_url: https://depth.brokensrc.dev/
repo_url: https://github.com/BrokenSource/DepthFlow/
nav:
  - Home:
    - index.md
    - About:
      - ğŸªµ Changelog: about/changelog.md
      - ğŸ§­ Roadmap: https://github.com/orgs/BrokenSource/projects/2
      - ğŸ’¬ Contact: about/contact.md
  - Installation:
    - get/index.md
    - ğŸ“¦ Installers: get/installers.md
    - ğŸ§€ Wheels: get/wheels.md
    - ğŸ”¥ Source: get/source.md
    - ğŸ³ Docker: get/docker.md
    - â˜ï¸ Cloud: get/cloud.md
  - Usage:
    - quickstart/index.md
    - ğŸ”´ Gradio WebUI: webui.md
    - ğŸŸ¡ Command line: commands.md
    - ğŸŸ¢ Python scripts: scripts.md
  - Documentation:
    - ğŸ”§ Parameters: parameters.md
    - ğŸ“œ Foundations: paper.md
  # - Code:
  #   - ğŸ“¦ Package: Code/
theme:
  custom_dir: ../../Website/overrides
  favicon: DepthFlow/Resources/Images/DepthFlow.png
markdown_extensions:
  pymdownx.snippets:
    base_path: [../../Website]
