name: make-website
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: BrokenSource/BrokenSource@main

      - name: Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"

      - name: Make Website
        run: uv run mkdocs gh-deploy --force --no-history
        working-directory: projects/${{github.event.repository.name}}
